In [40]:
from sqlalchemy import (create_engine,
                        inspect,
                        text,
                        select,
                        MetaData,
                        Table,
                        and_,
                        or_,
                        desc,
                        asc,
                        func
                        )

engine_903 = create_engine("sqlite+pysqlite://///workspaces/d2i-intermediate/Session 1/data/903_database.db")

connection = engine_903.connect()
inspection = inspect(engine_903)
inspection.get_table_names()

['ad1',
 'episodes',
 'header',
 'missing',
 'oc2',
 'oc3',
 'placed_for_adoption',
 'previous_permenance',
 'reviews',
 'uasc']

In [41]:
engine_chinook = create_engine("sqlite+pysqlite://///workspaces/d2i-intermediate/Session 1/data/chinook.db")
chinook_inspection = inspect(engine_chinook)
chinook_inspection.get_table_names()

['albums',
 'artists',
 'customers',
 'employees',
 'genres',
 'invoice_items',
 'invoices',
 'media_types',
 'playlist_track',
 'playlists',
 'tracks']

In [42]:
metadata_903 = MetaData()

episodes = Table('episodes', metadata_903, autoload_with=engine_903)

print(episodes.name)
print(episodes.c.keys())
print(repr(episodes))

episodes
['index', 'CHILD', 'DECOM', 'RNE', 'LS', 'CIN', 'PLACE', 'PLACE_PROVIDER', 'DEC', 'REC', 'REASON_PLACE_CHANGE', 'HOME_POST', 'PL_POST', 'URN']
Table('episodes', MetaData(), Column('index', INTEGER(), table=<episodes>), Column('CHILD', INTEGER(), table=<episodes>), Column('DECOM', TEXT(), table=<episodes>), Column('RNE', TEXT(), table=<episodes>), Column('LS', TEXT(), table=<episodes>), Column('CIN', TEXT(), table=<episodes>), Column('PLACE', TEXT(), table=<episodes>), Column('PLACE_PROVIDER', TEXT(), table=<episodes>), Column('DEC', TEXT(), table=<episodes>), Column('REC', TEXT(), table=<episodes>), Column('REASON_PLACE_CHANGE', TEXT(), table=<episodes>), Column('HOME_POST', TEXT(), table=<episodes>), Column('PL_POST', TEXT(), table=<episodes>), Column('URN', INTEGER(), table=<episodes>), schema=None)

In [43]:
metadata_chinook = MetaData()

albums = Table('albums', metadata_chinook, autoload_with=engine_chinook)

print(albums.name)
print(albums.c.keys())
print(repr(albums))

albums
['AlbumId', 'Title', 'ArtistId']
Table('albums', MetaData(), Column('AlbumId', INTEGER(), table=<albums>, primary_key=True, nullable=False), Column('Title', NVARCHAR(length=160), table=<albums>, nullable=False), Column('ArtistId', INTEGER(), ForeignKey('artists.ArtistId'), table=<albums>, nullable=False), schema=None)

In [44]:
with engine_903.connect() as con:
    stmt = "SELECT * FROM episodes"
    result_proxy = con.execute(text(stmt))
    results = result_proxy.fetchall()


first_row = results[0]
print(first_row)
print(first_row.CHILD)

(0, 566910, '15/02/2016', 'L', 'C2', 'N3', 'T2', 'PR0', '14/08/2017', 'X1', 'CLOSE', None, None, 4244474)
566910

In [45]:
with engine_chinook.connect() as con:
    stmt = "SELECT * FROM albums"
    result_proxy = con.execute(text(stmt))
    results = result_proxy.fetchall()

first_row = results[0]
print(first_row)

(1, 'For Those About To Rock We Salute You', 1)

In [46]:
with engine_903.connect() as con:
    stmt = select(episodes)
    result_proxy = con.execute(stmt)
    results = result_proxy.fetchmany(size=10)

results

[(0, 566910, '15/02/2016', 'L', 'C2', 'N3', 'T2', 'PR0', '14/08/2017', 'X1', 'CLOSE', None, None, 4244474),
 (1, 566910, '14/08/2017', 'T', 'C2', 'N3', 'A3', 'PR3', None, 'X1', None, 'EG19 7TT', 'WV27 9FW', 8969628),
 (2, 384923, '26/04/2016', 'T', 'L1', 'N8', 'A5', 'PR2', '09/05/2017', 'X1', None, 'EH14 8EC', 'WD10 6ZQ', 1157828),
 (3, 384923, '09/05/2017', 'L', 'C2', 'N8', 'A5', 'PR2', None, 'X1', 'CARPL', 'EH14 8EC', 'WD10 6ZQ', 1157828),
 (4, 709901, '07/04/2016', 'L', 'V3', 'N8', 'T3', 'PR2', '22/01/2018', 'X1', None, 'EE28 7VZ', 'WT9 9BG', 5814849),
 (5, 709901, '22/01/2018', 'L', 'C1', 'N8', 'T3', 'PR2', None, 'X1', 'APPRR', 'EE28 7VZ', 'WT9 9BG', 5814849),
 (6, 550084, '18/02/2017', 'L', 'J1', 'N5', 'A5', 'PR3', '05/11/2017', 'X1', 'PLACE', 'EJ21 9CG', 'WH25 3QS', 9755022),
 (7, 550084, '05/11/2017', 'P', 'J1', 'N5', 'R1', 'PR2', '19/11/2017', 'X1', 'ALLEG', 'ET6 7NV', 'WU1 8KL', 5874392),
 (8, 550084, '19/11/2017', 'P', 'J1', 'N5', 'T0', 'PR3', None, 'X1', 'PLACE', 'EY25 4DI', 'WV28 2FA', 3080792),
 (9, 710229, '01/06/2015', 'S', 'V2', 'N6', 'R5', 'PR2', '15/02/2018', 'E41', None, 'EK22 9AO', 'WS17 3TK', 1008465)]

In [47]:
with engine_chinook.connect() as con:
    stmt = select(albums)
    result_proxy = con.execute(stmt)
    results = result_proxy.fetchmany(size=10)

results

[(1, 'For Those About To Rock We Salute You', 1),
 (2, 'Balls to the Wall', 2),
 (3, 'Restless and Wild', 2),
 (4, 'Let There Be Rock', 1),
 (5, 'Big Ones', 3),
 (6, 'Jagged Little Pill', 4),
 (7, 'Facelift', 5),
 (8, 'Warner 25 Anos', 6),
 (9, 'Plays Metallica By Four Cellos', 7),
 (10, 'Audioslave', 8)]

In [48]:
import pandas as pd

header = Table('header',metadata_903, autoload_with=engine_903)

with engine_903.connect() as con:
    stmt = select(header).where(or_(header.columns.ETHNIC == "REFU",
                                    header.columns.ETHNIC == "NOBT"))

    result_proxy = con.execute(stmt)
    result = result_proxy.fetchall()
    print(stmt)

df_903 = pd.DataFrame(result)

df_903

SELECT header.index, header."CHILD", header."SEX", header."DOB", header."ETHNIC", header."UPN", header."MOTHER", header."MC_DOB"
FROM header
WHERE header."ETHNIC" = :ETHNIC_1 OR header."ETHNIC" = :ETHNIC_2

     index   CHILD  SEX         DOB ETHNIC            UPN MOTHER MC_DOB
0        1  384923    2  09/09/2011   REFU  L034811502612   None   None
1        4  710229    2  15/04/2002   REFU  Z095096287583   None   None
2       12  411080    1  30/07/2011   NOBT  O068405655286   None   None
3       17   50224    1  11/01/2003   REFU  U055331591206   None   None
4       40  638861    2  24/09/2009   REFU  J059828899095   None   None
..     ...     ...  ...         ...    ...            ...    ...    ...
260   2632  915763    1  18/07/2012   REFU  T096410853890   None   None
261   2639  899850    1  17/08/2005   NOBT  H026196808254   None   None
262   2649  524749    1  04/09/2007   REFU  V013391805789   None   None
263   2660  473732    1  17/06/2001   NOBT  Z044719942273   None   None
264   2662  815990    1  28/10/2009   REFU  H066890824766   None   None

[265 rows x 8 columns]

In [51]:


albums = Table('albums', metadata_chinook, autoload_with=engine_chinook)

with engine_chinook.connect() as con:
    stmt = select(albums).where(or_(albums.columns.ArtistId == 1,
                                    albums.columns.ArtistId == 2))

    result_proxy = con.execute(stmt)
    result = result_proxy.fetchall()
    print(stmt)

df_albums = pd.DataFrame(result)

df_albums

SELECT albums."AlbumId", albums."Title", albums."ArtistId"
FROM albums
WHERE albums."ArtistId" = :ArtistId_1 OR albums."ArtistId" = :ArtistId_2

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1
1        4                      Let There Be Rock         1
2        2                      Balls to the Wall         2
3        3                      Restless and Wild         2